= Vim Questions

[qanda]
What are the keystrokes that help exit to normal mode from insert/visual/normal mode?::
`Ctrl+c`, `Ctrl+[`, `Esc`.

Which keystroke starts the line wise visual mode?::
`Shift+v`.

Which keystroke starts the block wise visual mode?::
`Ctrl+v` or `Ctrl+Alt+v`.

Which command opens Vim's help?::
`:help`

Which command quits the current window?::
`:q`

Which command quits the current window without saving?::
`:q!`

Which command saves or writes your changes?::
`:w`.

Which command writes and quits the buffer window?::
`:wq` or `:x`

Which command opens a file for editing?::
`:e <path>`

How do you start searching a word within a buffer?::
`/`

Which key finds the next occurence of the search?::
`n`

Which key finds the previous occurence of the search?::
`N`

When in normal mode, which key searches the word under the cursor forwards?::
`*`

When in normal mode, which key searches the word under the cursor backswards?::
`#`

Which key will undo your last edit?::
`u`

Which key will redo your last change?::
`Ctrl+r`

Which key will move the cursor forward to the next word?::
`w`

Which key will move the cursor back to the previous word?::
`b`

Which key will move the cursor to the beginning of the current line?::
`0`

Which key will move the cursor to the first non blank character on the current line?::
`^`

Which key will move the cursor to the end of the current line?::
`$`

Which key will move the cursor to the matching bracket when the cursor is already on a bracket?::
`%`

Which key will help find a character after your cursor?::
`f<character>`

Which key will help find a character before your cursor?::
`F<character>`

Which key will move the cursor to a character after your cursor?::
`t<character>`

Which key will move the cursor to a character before your cursor?::
`T<character>`

Which key will move the cursor to the next character?::
`;`

Which key will move the cursor to the previous character?::
`,`

Which key will move the cursor to the beginning of the arbitrary line?::
`<line_number>G`

Which key will move the cursor to the last line of the file?::
`G`

Which key will move the cursor to the first line of the file?::
`1G` or `gg`

Which key will scroll the window downwards?::
`Ctrl+e`

Which key will move your cursor upward half the screen?::
`Ctrl+u`

Which key will move your cursor downward half the screen?::
`Ctrl+d`

In normal mode, which key is the operator for delete?::
`d`

In normal mode, which key is the operator for change?::
`c`

In normal mode, which key is the operator for yank (copy)?::
`y`

In normal mode, which key is the operator for pasting what you copied?::
`p` or `P`

Which key combination will help delete characters from your cursor to the end of the line?::
`d$` or `D`

Which key combination will delete everything from your cursor to the beginning of the file?::
`dgg`

Which key combination will delete everything in the file?::
`ggdG`

Which key combination will delete the current word under the cursor?::
`diw`

Which key combination will delete the current word under the cursor and switch to insert mode?::
`ciw`

Which key combination will delete inside the paragraph?::
`dip`

Which command unsets an option?::
`:set no<option>`

Which command toggles the option?::
`:set <option>!`

Which command returns the option's value?::
`:set <option>?`

Which command sets the option's value?::
`:set <option> = <value>`

Which command subtracts (in case of number) or deletes (in case of string) an option's value?::
`:set <option>-=<value>`

Which command resets the option to its default value?::
`:set <option>&`

Which command displays the filetype of the current open file?::
`:set filetype?`

Which help command will display more information about options?::
`:help options`

Which help command will display more information about options-list?::
`:help options-list`

What is a buffer?::
A buffer is an open file in memory.

What happens when you close a buffer?::
It goes into hidden state.

When you close a buffer, does it close the file too?::
No. When you close a buffer it does not close the file. The buffer just moves to hidden state.

What are the three different types of buffer states?::
active, hidden, inactive

What is the inactive state of a buffer?::
The buffer is not linked to any file and is not displayed and is empty.

Which command displays the list of open buffers?::
`:buffers`

Which command displays a buffer with a certain name or id?::
`:buffer <ID_or_Name>`

Which command displays the next buffer?::
`:bnext` or `:bn`

Which command displays the previous buffer?::
`:bprevious` or `:bp`

Which command displays the first buffer?::
`:bfirst` or `:bf`

Which command displays the last buffer?::
`:blast` or `:bl`

What is an alternate buffer?::
It is indicated in your buffer list with the symbol `#`.

Which command switches to the alternate buffer?::
`:Ctrl+^`

Which command helps switch to a specific buffer ID?::
`<ID>Ctrl+^`

Which command will you use to switch to a buffer with an ID of 75?::
`75Ctrl+^`

Which command helps apply a command to all buffers?::
`:bufdo <command>`

Which command displays a list of unlisted buffers?::
`:buffers!` or `:ls!`

How do you create a new file in a buffer?::
`:badd <filename>`

How do you delete a buffer with an ID or name?::
`:bdelete <ID_or_Name>`

Write a command that will delete a buffers from ID 1 to ID 10?::
`1,10bdelete`

Write a command that will delete all buffers?::
`%bdelete`

Which help command will display information about buffers?::
`:help buffers` and `:help :buffers`

What is a window?::
It is a space you can use to display the contents of a buffer.

How can you split the current window horizontally?::
`Ctrl+W s`

How can you split the current window vertically?::
`Ctrl+W v` or `Ctrl+Alt+W v`

How can you split the current window with the alternate file?::
`Ctrl+W ^`

How will split the current window with the buffer of id `<ID>`?::
`<buffer_id>Ctrl+W`

How will you move the cursor to the bottom window?::
`Ctrl+W j`

How will you move the cursor to the top window?::
`Ctrl+W k`

How will you move the cursor to the left window?::
`Ctrl+W h`

How will you move the cursor to the right window?::
`Ctrl+W l`

How will you rotate the window?::
`Ctrl+W r`

How will you exchange with the next window?::
`Ctrl+W x`

How will you resize windows for them to fit on the screen with the same size?::
`Ctrl+W =`

How will you decrease a window's height?::
`Ctrl+W -`

How will you increase a window's height?::
`Ctrl+W +`

How will you quit the current window?::
`:q`

How will you quit the current window with an unsaved buffer?::
`:q!`

What are tabs?::
Tabs are a container for a bunch of windows.

Are tabs in nvim the same as tabs in an IDE?::
No they are a different concept.

How do you open a new tab?::
`:tabnew` or `:tabe`

How do you close the current tab?::
`:tabclose` or `:tabc`

How do you close every other tab except the current one?::
`:tabonly` or `:tabo`

How do you go to the next tab?::
`gt`

How do you go to the previous tab?::
`gT`

How do you go to the first tab?::
`1gT`

What is an argument list?::
The argument list allows you to organize your open files.

How can you create a new keystroke mapping for NORMAL mode?::
`:nmap`

How will you create a new keystroke mapping for INSERT mode?::
`:imap`

How will you create a new keystroke mapping for VISUAL mode?::
`:xmap`

How will you create a new keystroke mapping for COMMAND-LINE mode?::
`:cmap`

How will you create a non recursive keystroke mapping for NORMAL mode?::
`:nnoremap`

How will you create a non recursive keystroke mapping for INSERT mode?::
`:inoremap`

How will you create a non recursive keystroke mapping for VISUAL mode?::
`:vnoremap`

How will you create a non recursive keystroke mapping for COMMAND-LINE mode?::
`:cnoremap`

How will you define the character Space while creating keystroke mappings?::
`<space>`

How will you define `Ctrl+W` while creating keystroke mappings?::
`c-w`

How will you define carriage return (Enter) while creating keystroke mappings?::
`<cr>`

How will you define the escape character while creating keystroke mappings?::
`<esc>`

What is the help command that will give more information about keys?::
`:help key-notation`

How will you jump to the previous cursor position in the jump list?::
`Ctrl+o`

How will you jump to the next cursor position in the jump list?::
`Ctrl+i`

How can you display your jump list?::
`:jumps`

What is a jump list?::
Each time we use a jump motion, the position of the cursor before the jump is saved in the jump list.

What is a change list?::
Each time you insert something the position of the cursor is saved in the change list.

How will you jump to the next change in the change list?::
`g;`

How will you jump to the previous change in the change list?::
`g,`

How will you jump to the start of a method?::
`[m`

How will you jump to the end of a method?::
`]m`

How will you repeat the last change?::
`.`

How will you repeat the last command executed?::
`@:`

What are the steps to create a macro?::
. `q<lowercase_letter>` - Begins the capturing of keystrokes.
. `q` - stops the capture of keystrokes.
. `@<lowercase_letter>` - Executes the keystrokes.

How will you repeat the previous command?::
`@@`

What is the suggested best practice to create a new mapping?::
To use a special key called the _leader_ key.

How do you set a leader key?::
Set the variable mapleader to your leader key. +
`:let mapleader = "<space>"`

Remap the `:bn` command to use the leader key `<space>`?::
`:let mapleader = "<space>"` +
`:nnoremap <leader>bn :bn<cr>`

What is the command to open the help file for more information on mapping?::
`:help mapping`

What is the command to open the help file for more information on leader?::
`:help leader`

Which command opens the command line history?::
`q:`

Which command opens the search feature for the history?::
`q/` and `q?`

Which command opens a command line history while in COMMAND LINE mode?::
`Ctrl+f`

Which command also opens the command line history?::
`:history`

Which command opens the help for the command line window?::
`:help cmdline-window`

Which command opens the help for the history command?::
`:help 'history'`

How can you represent a line number range?::
`<number>` - Any number `<number>` in your range refers to a line number.

How can you represent the current line in a range?::
`.` - represents a current line in a range.

How can you represent the last line of the current buffer in a range?::
`$` - represents the last line of the current buffer.

How can you represent the entire file in a range?::
`%` - represents the entire file (same as `1,$`).

How can you represent the last selection you made during the last VISUAL mode in a range?::
`*` - use the last selection you've made during the last VISUAL mode.

Write a command that will delete lines 1 to 40?::
`:1,40d`

Write a command that will delete from the second line till the end of the file?::
`:2,$d`

Write a command that will delete from the current line till the end of the file?::
`:.,$d`

Write a command that will delete every line of a file?::
`:%d`

What are quickfix lists?::
A quickfix list is a set of positions in one or multiple files.

What happens when you run the command `:vimgrep hello *`?::
. It will search the pattern "hello" in every file of your working directory.
. It will populate a quickfix list with every position matching your pattern "hello".
. It will move your cursor to the first position of the quickfix list.

What is a quickfix list often used for?::
The quickfix list is often used to display specific errors in a codebase, often spit out from a compiler or a linter.

Which command will display the current quickfix list?::
`:cl` or `:clist`

Which command will move to the `<number>` entry of the current quickfix list?::
`:cc <number>`

Which command will move to the next entry of the current quickfix list?::
`cnext` or `:cn`

Which command will move to the previous entry of the current quickfix list?::
`:cprevious` or `:cp`

Which command will move to the first entry of the current quickfix list?::
`:cfirst` or `:cfir`

Which command will move to the last entry of the current quickfix list?::
`:clast` or `:clas`

How will you execute a command `<cmd>` on each valid entry of the current quickfix list?::
`:cdo <cmd>`

How can you create a quickfix list using the result of a Vimscript extension `<expr>`?::
`:cexpr <expr>` or `:cex <expr>`

Which command will empty your current quickfix list?::
`:cex []`

Which command will populate your quickfix list with the output of any shell command like `ls`?::
`:cex system("ls")`

How can you append the result of a vimscript expression to the current quickfix list?::
`:caddexpr <expr>` or `:cadde <expr>`

Which command opens the current quickfix list in a new buffer window?::
`:copen` or `:cope`

What is a location list?::
A location list is similar to a quickfix list, except that a location list is local to a window and a quickfix list is global to your Vim instance. +
You can have one location list per open window. +
You can have access to only one quickfix list.


What is a register??::
Registers are places where you can read and write some text. +
Think of them as Vim's clipboard.

How will you display the contents of a register?::
`:registers` or `:reg`

Which keystroke specifies the register `<reg>` to be read or written?::
`"<reg>`

How will you write to a register?::
To write to a register:
* Hit `"a` in NORMAL mode to specify what register you want to write on.
* Yank, change or delete some content to write it to register `a`.
** for example, by using `dd` in normal mode.

How will you read from a register `a`?::
* Hit `"a` in NORMAL mode to specify what register you want to read.
* Use a put keystroke in NORMAL mode to spit out the content of the register in your current buffer.
** An example of a put keystroke is a `P` or `p` command.

How many types of registers are there in Vim?::
There are 10 different types of registers.

What does the unnamed register contain?::
It contains the last deleted, changed, or yanked content even if one register is specified.

How will you paste content present in the unnamed register?::
`""p`

What does the `0` numbered register contain?::
The content of the last yank.

How will you paste content present in the last yank using a register?::
`"0`

What do the numbered registers `1` to `9` contain?::
They contain the content you have deleted or changed.
+
. Each time you delete or change content, it will be added to register `1`.
. The previous content of the register `1` will be assigned to register `2`, the previous content of `2` to `3`...
. When something is added to the register `1`, the content of the register `9` is lost.
+
None of these registers are written if you've specified one before with the keystroke `"`.

What is the small delete register?::
The `-` register. +
It contains any deleted or changed content smaller than one line. +
It is not written if you specified a register with `"`.

What are named registers?::
They range from `a` to `z`. +
Vim will never write to them if you do not specify the keystroke `"`. +
You can use the uppercase name of each register to append to it (instead of over-writing it).

What are read only registers?::
They are `".`, `"%` and `":`. +

* `.` contains the last inserted text.
* `%` contains the name of the current file.
* `:` contains the most recent command line executed. 

What is an alternate buffer register?::
It is `#`. +
It contains the alternate buffer for the current window.

What is an expression register?::
It is `"=`.
It stores the result of an expression.

What are the selection registers?::
They are `"+` and `"*`.

* `+` is synchronized with the system clipboard.
* `*` is synchronized with the selection clipboard (only on *nix systems).

What is a black hole register?::
It is the `"_` register. +
Everything written in there will disappear forever.

What is the last search pattern register?::
This register contains your last search. +
It is the `"/` register.

What gets output when the put command is used without specifying the register?::
It will output the unnamed register by default.

What happens when you add the line `clipboard+=unnamedplus` to your vimrc?::
In this case, the content you change, delete, or yank will go directly in the unnamed register and the `+` register. 

Using the put commands will directly output the `+` register too.

Many find it useful to access the OS clipboard more easily, without the need to specify the `+` register for reading and writing it.

How can you append to your macro recording?::
. Hit `qa` and record whatever keystrokes you want.
. Stop the recording by hitting `q` again.
. You realize that you forgot a couple of keystrokes.
. Execute your keystrokes to be sure you are at the last position of your recording.
. Hit `qA` to _append_ to your register `a`.
. When you are done, hit `q` again.

How can you paste or use the content of a register in INSERT mode or COMMAND LINE mode?::
`Ctrl+R<reg>` to put the content of `<reg>` in your current buffer.


What is an expression register?::
It can evaluate custom functions that you have defined while staying in insert mode.

Give an example of how you can use an expression register?::
. Switch to INSERT mode and hit keystroke `Ctrl+r =`.
. You will move to the Vim's command line.
. Type any vimscript expression you want, like `system("ls")` or `4+4`.
. Hit `Enter` to run the expression.
. The output of the shell command `ls` is directly inserted in the buffer.

How can you clear a register?::
`qaq` +
Beginning a recording also deletes everything which is in this register. +
So you need to just stop the recording by hitting q again to have an empty register.


What is a substitution?::
A substitution is a way to replace some content with some other content, using a range and a count. +
The count will decide how many lines is affected by your substitution from the last line of your range.

What is the default range of a substitution command?::
The default range is the current line if you do not specify it.

What is the pattern of the substitution command?::
`:s/pattern/replacement/flags`

* *pattern* is the search you want to match.
* *replacement* will replace the first match of the pattern on each line.
* *flag* modify the behaviour of the command.

Is the *replacement* mandatory in a substitution command?::
No, if you omit it, the substitute command will delete the pattern matched.
