= Delay and Run Method 
:title: Delay and Run Method 
:navtitle: Delay and Run Method 
:source-highlighter: highlight.js
:highlightjs-languages: fsharp

Avoiding unnecessary evaluations.

We want to use the “return” keyword to return early and stop any more processing being done. +
return and yield do not generate an early return from a computation expression. +
The entire computation expression, all the way to the last curly brace, is always evaluated and results in a single value.

This is a problem, because you might get unwanted side effects and your code is doing something unnecessary, which might cause performance problems.

Use the delay method to do this. +
Any result from Return or Yield is immediately wrapped in a “delay” function like this, and then you can choose whether to run it or not.


[source,fsharp]
----
module TraceBuilder =

    type TraceBuilder() =

        member this.Bind(m, f) =
           match m with
           | None ->
               printfn "Binding with None. Exiting."
           | Some a ->
               printfn "Binding with Some(%A). Continuing" a
           Option.bind f m

        member this.Return(x) =
           printfn "Return an unwrapped %A as an option" x
           Some x

        member this.Zero() =
           printfn "Zero"
           None

        member this.Combine (a,b) =
           printfn "Returning early with %A. Ignoring second part: %A" a b
           a

        member this.Run(funcToRun) =
           let runResult = funcToRun()
           runResult // return the result of running the delayed function

        member this.Delay(f) =
            printfn "Delay"
            f

    //make a new instance
    let trace = new TraceBuilder()

    (*
        Assign the output of the computation expression to a function value, say f, and then evaluate it.
    *)
    let f = trace {
        printfn "Part 1: about to return 1"
        return 1
        printfn "Part 2: after return has happened"
        }
    f |> printfn "Result for Part1 without Part2: %A"
----

The Run method exists for exactly this reason. +
It is called as the final step in the process of evaluating a computation expression, and can be used to undo the delay.

